#!/usr/bin/env python3

import subprocess
import sys
import os

deps = [ "psycopg2", "pyqt6", "pandas", "pd", "openpyxl", ]

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

def main ():
    for dep in deps:
        install (dep)

if __name__ == "__main__":
    main()
